org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
# parchment_minecraft_version e parchment_mappings_version removidos por enquanto (ver build.gradle)
# Mod Properties
mod_version=0.8.0-26.2-dev
maven_group=cn.sh1rocu
archives_base_name=TACZ-Refabricated
# Dependencies
fabric_version=0.155.2+26.2
jei_version=30.7.0.39
cloth_config_fabric=26.2.155
embeddedt_id=5522040
carry_on_id=4882498
player_animation_lib=1.0.2-rc1+1.20
rhino_version=2001.2.3-build.6
architectury_version=9.2.14
kubejs_version=2001.6.5-build.14
rei_version=12.1.785